---
title: "10 Texts to Freak Out Your Mom"
author: "Jack Lord"
date: "2017-08-25"
slug: "ten-texts-to-freak-out-your-mom"
categories: ["Fiction"]
type: "post"
---

## #1

> It's not just gunshot residue we need to worry about. We need to burn those clothes, Mike, not just wash them.

## #2

> How deep did you even dig that hole, Mike? You were only out there for like twenty minutes, and you were singing the whole time, so how hard could you even have been digging?

## #3

> God-damn it, Mike. I went and looked in that hole and there's nothing in it.

## #4

> I didn't like the idea of cooking meth with the ashes of our fallen enemies the first time I heard it, Mike.

## #5 

> That was a pretty big fire but I've got to hand it to you, Mike, we did get away with a lot of chemicals.

## #6

> What the hell was in that batch, Mike? What have we done?

## #7 

> Mike: my guy at the morgue says they are having to order coffins in special shapes.

## #8

> I checked out your qualifications, Mike. The University of Michitosa doesn't even HAVE a biochemistry department. Are you even QUALIFIED to cook meth?

## #9

> Meet me at the cabin, Mike. There's a lot of heat on us right now. Come alone. We need to clean. shit. up.

## #10

> No, mom, everything's fine. Mike's rent was due, that's all. Round soon for some home cooking! x

## #11

> Mike, it's too risky to talk about you-know-what over the phone, so I'll just post everything we need to discuss on my blog, disguised as one of those 'texts to freak out your Mom' things. There's only one entry now, but I'll just edit it as we go along. Check it A LOT, OK?